In [18]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
import random
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
import emoji

In [19]:
# read reviews csv
df = pd.read_csv('reviews.csv')
df.head()

reviews  label
0  kemeja nya bagusss bgtttt😍😍😍aaaa mauuu nngisss...    1.0
1  Jahitannya sih rapi,cuman ada benang yang ikut...    0.0
2  Sesuai harga. Agak tipis tapi masih oke kok. W...    0.0
3  Wah gila sihhh sebagus itu, se worth it, se  l...    1.0
4  Kain nya bagus halus  \nTapi kok di bukak koto...    0.0

In [20]:
df['reviews'] = df['reviews'].apply(lambda s: emoji.replace_emoji(s, ' '))
df.head()

reviews  label
0  kemeja nya bagusss bgtttt   aaaa mauuu nngisss...    1.0
1  Jahitannya sih rapi,cuman ada benang yang ikut...    0.0
2  Sesuai harga. Agak tipis tapi masih oke kok. W...    0.0
3  Wah gila sihhh sebagus itu, se worth it, se  l...    1.0
4  Kain nya bagus halus  \nTapi kok di bukak koto...    0.0

In [21]:
text = df['reviews'].tolist()
text

['kemeja nya bagusss bgtttt   aaaa mauuu nngisssss   knpa ga dri dlu beli kemeja ditoko ini , ini kemejanya asli emg bagus, bahannya jga adem ga gerah,and ga nerawang jga... itu krna camera nya jelek jdi ga trlalu jelas kemejanya.. asliny baguss bgttt ga bhong sumpah',
 'Jahitannya sih rapi,cuman ada benang yang ikut ke jahit juga jadi agak jelek',
 'Sesuai harga. Agak tipis tapi masih oke kok. Warnanya abu tapi kalo difoto emang kayak biru dikit. Thanks sellerr',
 'Wah gila sihhh sebagus itu, se worth it, se  lembut itu bajunya,,,, kirain bakal terlalu tipis ky kemeja ku yg lama ternyata sedikit ky kaos bajunya baklgus bettt dah dgn harga segitu sih worth it thankyou yh,, next bakal order lgi',
 'Kain nya bagus halus  \nTapi kok di bukak kotor ya warna putih lagi',
 'baguss dehh dengan harga segitu kainnya juga ga tipis" banget dan ga tebel" banget, kalo putih emang harus pake daleman biar ga nerawang bagussss pengiriman juga ga lama',
 'Harga mahal bahan tipis banget. Pengiriman lama

In [28]:
y = df['label']
y = tf.keras.utils.to_categorical(y)
y

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [29]:
df['label'].value_counts()

label
0.0    446
1.0    385
Name: count, dtype: int64

In [30]:
token = tf.keras.preprocessing.text.Tokenizer()
token.fit_on_texts(text)
token.index_word
# print token type
print('Token type: ', type(token))

Token type:  <class 'keras.preprocessing.text.Tokenizer'>


In [31]:
vocal = len(token.index_word) + 1
vocal

2924

In [32]:
encode_text = token.texts_to_sequences(text)
print(encode_text)

[[202, 1, 166, 647, 827, 1206, 1207, 1208, 4, 1209, 648, 10, 202, 225, 6, 6, 321, 299, 455, 9, 33, 322, 48, 4, 456, 540, 4, 144, 322, 64, 252, 1210, 1, 90, 236, 4, 828, 395, 321, 1211, 88, 253, 4, 1212, 156], [541, 30, 348, 149, 18, 829, 13, 1213, 77, 1214, 19, 58, 26, 90], [28, 21, 26, 44, 12, 254, 78, 59, 99, 157, 12, 96, 457, 100, 130, 275, 203, 237, 1215], [830, 255, 349, 256, 64, 831, 177, 158, 831, 178, 64, 167, 276, 138, 91, 44, 649, 202, 204, 3, 17, 74, 187, 649, 650, 167, 1216, 1217, 205, 188, 21, 92, 30, 177, 158, 396, 832, 123, 138, 34, 277], [397, 1, 9, 350, 12, 59, 2, 1218, 278, 35, 11, 139, 20], [88, 542, 41, 21, 92, 257, 19, 4, 44, 7, 8, 4, 238, 7, 96, 139, 100, 226, 140, 651, 227, 4, 144, 279, 22, 19, 4, 17], [21, 131, 27, 44, 7, 22, 17, 12, 11, 258, 189, 543, 14, 28, 179, 32, 2, 398], [259, 159, 399, 544, 90, 206, 43, 104, 1219, 74, 45, 120, 166], [26, 5, 545, 105, 50, 11, 1220, 54, 458, 260, 400, 2, 190, 20, 150, 111], [189, 652, 546, 180, 68, 179, 168, 28, 132, 833, 

In [33]:
max_kata = 100
X = tf.keras.preprocessing.sequence.pad_sequences(encode_text, maxlen=max_kata, padding='post') 
X

array([[202,   1, 166, ...,   0,   0,   0],
       [541,  30, 348, ...,   0,   0,   0],
       [ 28,  21,  26, ...,   0,   0,   0],
       ...,
       [ 86,  15,  23, ...,   0,   0,   0],
       [ 53,  66,  49, ...,   0,   0,   0],
       [ 16,  32,  75, ...,   0,   0,   0]])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
x_train = np.array(x_train)
x_test = np.array(x_test)

y_train = np.array(y_train)
y_test = np.array(y_test)

x_train.shape

(664, 100)

In [23]:
vec_size = 300
max_kata = 100
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocal, vec_size, input_length=max_kata),
    tf.keras.layers.Conv1D(64, 8, activation='relu'),
    tf.keras.layers.MaxPooling1D(2),
    tf.keras.layers.Dropout(0.5),
    
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.GlobalMaxPooling1D(),
    tf.keras.layers.Dense(2, activation='sigmoid')
])

model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 100, 300)          877200    
                                                                 
 conv1d_1 (Conv1D)           (None, 93, 64)            153664    
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 46, 64)           0         
 1D)                                                             
                                                                 
 dropout_1 (Dropout)         (None, 46, 64)            0         
                                                                 
 dense_3 (Dense)             (None, 46, 32)            2080      
                                                                 
 dense_4 (Dense)             (None, 46, 16)            528       
                                                      

In [24]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
21/21 [==============================] - 1s 11ms/step - loss: 0.6923 - accuracy: 0.5181 - val_loss: 0.6826 - val_accuracy: 0.5449
Epoch 2/10
21/21 [==============================] - 0s 7ms/step - loss: 0.6570 - accuracy: 0.5572 - val_loss: 0.6344 - val_accuracy: 0.6168
Epoch 3/10
21/21 [==============================] - 0s 7ms/step - loss: 0.5173 - accuracy: 0.7756 - val_loss: 0.4486 - val_accuracy: 0.8563
Epoch 4/10
21/21 [==============================] - 0s 6ms/step - loss: 0.2171 - accuracy: 0.9518 - val_loss: 0.2413 - val_accuracy: 0.9222
Epoch 5/10
21/21 [==============================] - 0s 7ms/step - loss: 0.0574 - accuracy: 0.9864 - val_loss: 0.2491 - val_accuracy: 0.8922
Epoch 6/10
21/21 [==============================] - 0s 6ms/step - loss: 0.0169 - accuracy: 0.9985 - val_loss: 0.2453 - val_accuracy: 0.8922
Epoch 7/10
21/21 [==============================] - 0s 6ms/step - loss: 0.0055 - accuracy: 1.0000 - val_loss: 0.2462 - val_accuracy: 0.8922
Epoch 8/10
21/21 [=

In [34]:
def get_encode(x):
    x = token.texts_to_sequences(x)
    x = tf.keras.preprocessing.sequence.pad_sequences(x, maxlen=max_kata, padding='post')
    return x

In [35]:
x = ['penjual nya tidak ramah']
get_encode(x)

array([[216,   1,  61, 362,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [36]:
model.predict(get_encode(x))

1/1 [==============================] - 1s 1s/step


array([[0.90606374, 0.3917901 ]], dtype=float32)

In [37]:
def decode_predict(pred):
    return 'negatif' if pred[0][0] > pred[0][1] else 'positif'

decode_predict(model.predict(get_encode(x)))

1/1 [==============================] - 0s 15ms/step


'negatif'

In [38]:
model.save('model.h5')